# Generated by Django 4.0.3 on 2022-12-15 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40, null=True)),
                ('Company_name', models.CharField(max_length=40, null=True)),
                ('Company_address', models.CharField(max_length=100, null=True)),
                ('Shipping_location', models.CharField(max_length=100, null=True)),
                ('Phone_no', models.CharField(max_length=40, null=True)),
                ('Email', models.CharField(max_length=40, null=True)),
                ('Owner', models.TextField(max_length=40, null=True)),
                ('Container_id', models.CharField(max_length=100, null=True)),
                ('Status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='lessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Phone_number', models.CharField(max_length=30)),
                ('Company_name', models.CharField(max_length=30)),
                ('Country', models.CharField(max_length=30)),
                ('Email_id', models.CharField(max_length=40)),
                ('Username', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=10)),
                ('Status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Phone_number', models.CharField(max_length=30)),
                ('Country', models.CharField(max_length=30)),
                ('Email_id', models.CharField(max_length=40)),
                ('Username', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=10)),
                ('Status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40, null=True)),
                ('Container_id', models.CharField(max_length=40, null=True)),
                ('Rate', models.CharField(max_length=40, null=True)),
                ('Container_type', models.CharField(max_length=40, null=True)),
                ('Container_length', models.CharField(max_length=40, null=True)),
                ('Container_material', models.CharField(max_length=40, null=True)),
                ('Container_condition', models.CharField(max_length=40, null=True)),
                ('Location', models.CharField(max_length=100, null=True)),
                ('Description', models.TextField(max_length=500, null=True)),
                ('Picture', models.FileField(null=True, upload_to='')),
                ('Owner', models.TextField(max_length=40, null=True)),
                ('Status', models.BooleanField(default=False)),
            ],
        ),
    ]
